Article/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import article_index,add_article,awal_article,getDataArticleAPI,daftarDataArticleAPI,json
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',awal_article, name='awal'),
    path('add-article',add_article,name='add article'),
    path('<str:post>',article_index,name='article index'),
    path('add-article/data-api', daftarDataArticleAPI, name='daftar'),
    path('add-article/data-article/<waktu>',getDataArticleAPI,name='data'),
    path('add-article/json',json,name='json')
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

internal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from homepage.views import index
from FeedbackPage.views import feedbackForm
from userpage.views import loginflutter, registFlutter, user_regist, loginpage, logoutuser,json, UserValidation, UserEmailValidation, PasswordValidation, user_regist_admin
from profileuser.views import get_user_data, user_profile
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name='home'),
    path('json/', json, name="json"),
    path('register/', user_regist, name='register'),
    path('register-admin/', user_regist_admin, name='register-admin'),
    path('get-profile/json', get_user_data, name='get-user-data'),
    path('login/', loginpage, name='login'),
    path('logout/', logoutuser, name='logout'),
    path('article/',include('Article.urls'), name='home'),
    path('registervaccine/', include('registervaccine.urls'), name='registervaccine'),
    path('profile/', include('profileuser.urls')),
    path('register/flutterregist', registFlutter, name="flutter-regist"),
    path('login/flutterlogin', loginflutter, name="flutter-login"),
    path('register/validation-username/', csrf_exempt(UserValidation.as_view()), name='validation-username'),
    path('register/validation-email/', csrf_exempt(UserEmailValidation.as_view()), name='validation-email'),
    path('register/validation-password/', csrf_exempt(PasswordValidation.as_view()), name='validation-password'),
    path('FeedbackPage', feedbackForm),
    path('registrasi/', include('kalender.urls')),
    path('randomgenerator/', include('randomgenerator.urls'), name='randomgenerator'),
]

registervaccine/urls.py
from django.urls import path
from .views import index, json, delete, daftar, getDataPendaftarAPI, daftarDataPendaftarAPI, get_user_name

app_name = 'registervac'
urlpatterns = [
    path('', index, name='index'),
    path('daftar/<event_id>', daftar, name='daftar'),
    path('json', json, name='json'),
    path('json', json, name='json_vaccine'),
    path('datapendaftarapi/<nama_user>', getDataPendaftarAPI, name='data_pendaftar_API'),
    path('dataapi', daftarDataPendaftarAPI, name='daftar_data_pendaftar_API'),
    path('delete/', delete, name='delete'),
    path('getusername', get_user_name),
]

registervaccine/models.py
from django.db import models
from kalender.models import Event

# Create your models here.
class DataPendaftar(models.Model):
    username = models.CharField(max_length=100)
    tanggal_vaksin = models.DateField()
    waktu_vaksin = models.CharField(max_length=100)
    NIK = models.BigIntegerField()
    name = models.CharField(max_length=40)
    age = models.IntegerField()

registervaccine/forms.py
from kalender.models import Event
from .models import DataPendaftar
from django import forms

class FormPendaftaran(forms.ModelForm):
    username = forms.CharField(disabled=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    tanggal_vaksin = forms.DateField(disabled=True, widget=forms.DateInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'yyyy-mm-dd'
        }
    ))
    waktu_vaksin = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))
    NIK = forms.IntegerField(widget=forms.NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Input your NIK (e.g. 3201123456780009)'
        }
    ))
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Input your full name'
        }
    ))
    age = forms.IntegerField(widget=forms.NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Input your age'
        }
    ))
    # added by Fauzan Andri
    event = forms.CharField(disabled=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    class Meta:
        model = DataPendaftar
        fields = ['username', 'tanggal_vaksin', 'waktu_vaksin', 'NIK', 'name','age']

registervaccine/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import FormPendaftaran
from django.http.response import HttpResponse
from django.core import serializers
from .models import DataPendaftar
from kalender.models import Event
from django.http import JsonResponse
import datetime
from django.views.decorators.csrf import csrf_exempt
import json as mdjson

# Create your views here.
@login_required(login_url='login')
def index(request):
    context = {}
    form = FormPendaftaran(request.POST or None)
    form.fields['username'].initial = request.user

    tanggal = request.GET.get('tanggal')
    bulan = request.GET.get('bulan')
    tahun = request.GET.get('tahun')

    if (type(tanggal) is str):
        intended_tanggal = tanggal + ' ' + bulan + ' ' + tahun
        form.fields['tanggal_vaksin'].initial = datetime.datetime.strptime(intended_tanggal, '%d %m %Y')

    if (form.is_valid and request.method == 'POST'):
        form.save()

    context['form'] = form
    return render(request, 'register_vaccine.html', context)

def daftar(request, event_id):
    context = {}
    form = FormPendaftaran(request.POST or None)
    event = Event.objects.get(id=event_id)
    waktu = event.start_time.strftime("%H:%M") + " - " + event.end_time.strftime("%H:%M")

    form.fields['username'].initial = request.user
    # Added by Fauzan Andri
    form.fields['event'].initial = event_id
    form.fields['tanggal_vaksin'].initial = event.date
    form.fields['waktu_vaksin'].initial = waktu

    if (form.is_valid and request.method == 'POST'):
        form.save()

    context = {
        'form': form,
        'event': event
    }

    return render(request, 'register_vaccine.html', context)

@csrf_exempt
def getDataPendaftarAPI(request, nama_user):
    # Method ini mengembalikan json yang dibutuhkan sesuai argumen nama_user.
    # Method ini akan dipanggil dari mobile app sebagai semacam A
    if (request.method == 'POST'):
        objek = DataPendaftar.objects.filter(username=str(nama_user))
        if (objek):
            dct = {
                'tanggal_vaksin': (objek.values_list('tanggal_vaksin')[0])[0].strftime('%d-%m-%Y'),
                'waktu_vaksin': (objek.values_list('waktu_vaksin')[0][0]),
                'nik': (str(objek.values_list('NIK')[0][0])),
                'nama': (objek.values_list('name')[0][0]),
                'umur': (str(objek.values_list('age')[0][0])),
            }
            return JsonResponse(dct)
        else:
            dct = {}
            return JsonResponse(dct, status=404)

@csrf_exempt
def daftarDataPendaftarAPI(request):
    # Inspired from https://stackoverflow.com/questions/40059654/python-convert-a-bytes-array-into-json-format/40060181
    
    if (request.method == 'POST'):
        data = mdjson.loads(request.body)
        username = data["username"]
        tanggal_vaksin = data["tanggal_vaksin"]
        waktu_vaksin = data["waktu_vaksin"]
        nik = data["nik"]
        nama = data["nama"]
        usia = data["usia"]
        
        dataPendaftarBaru = DataPendaftar(username = username, 
        tanggal_vaksin = tanggal_vaksin,
        waktu_vaksin = waktu_vaksin,
        NIK = nik,
        name = nama,
        age = usia)
        dataPendaftarBaru.save()

        return JsonResponse({'status': 200})

@login_required(login_url='login')
def json(request):
    # Pake ini di AJAX, trus diubah jadi object javascript, tinggal dipake
    # buat nampilin yang udah didaftarin di html-nya
    data = serializers.serialize('json', DataPendaftar.objects.filter(username=request.user))
    return HttpResponse(data, content_type="application/json")

@login_required(login_url='login')
def get_user_name(request):
    print('masuk sini mas brooo')
    user_name = '[{' + '"username": ' + '"' + str(request.user) + '"' + '}]'
    return HttpResponse(user_name, content_type="application/json")


def delete(request):
    data = list(DataPendaftar.objects.values())
    pk_number = request.GET.get('pk')
    DataPendaftar.objects.filter(id=int(pk_number)).delete()
    return JsonResponse(data, safe=False)

registervaccine/templates/register_vaccine.html
{% extends 'master.html' %}
{% load static %}

    {% block meta %}
    <link rel="stylesheet" href="{% static 'css/register_css.css' %}" />
    <title>{%block title%}Register Vaccination{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <!-- Logic of Document -->
    <script>
        $(document).ready(function(){
            $.ajax({
                url: "{% url 'registervac:json_vaccine' %}",
                dataType: 'json',   
                success: function(data) {
                    let dataPendaftar;
                    if (typeof data[0] === "undefined") {
                        dataPendaftar = `
                        <h1 class="display-2">Book a Vaccine Now!</h1>
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <br />
                            <input type="submit" class="btn btn-primary" value="Book Now!">
                        </form>`;
                    }
                    else {
                        dataPendaftar = `
                        <div class="card img-fluid">
                            <img class="card-img-top" src="{% static "image/covid.jpg" %}" alt="Covid Image" style="width:100%;">
                            <div class="card-img-overlay text-center" style="padding-top:25%">
                                <h4 class="card-title display-3" style="color:white; font-weight: bold;">Vaccination Booking Data</h4>
                                <p class="card-text">
                                    <p class="display-6" style="color:white; font-weight: bold;">Tanggal Vaksin: ${data[0].fields.tanggal_vaksin}</p>
                                    <p class="display-6" style="color:white; font-weight: bold;">NIK: ${data[0].fields.NIK}</p>
                                    <p class="display-6" style="color:white; font-weight: bold;">Name: ${data[0].fields.name}</p>
                                    <p class="display-6" style="color:white; font-weight: bold;">Age: ${data[0].fields.age}</p>
                                </p>
                                <button class="delete btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-modal">
                                    <h3><small>Delete</small></h3>
                                </button>
                            </div>
                        </div>`;
                    }
                    $('.konten-utama').html(dataPendaftar);
                    $('.konten-utama').fadeIn(1000);
                    
                    $('.delete').click(function(){
                        $('.confirm').click(function() {

                            $.ajax({
                            url: '{% url "registervac:delete" %}',
                            data: {
                                'pk': data[0].pk
                            },
                            dataType: 'json',
                            success: function(data) {
                                let dataPendaftar = `
                                <h1 class="display-2">Book a Vaccine Now!</h1>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    {{ form }}
                                    <br />
                                    <input type="submit" class="btn btn-primary" value="Book Now!">
                                </form>`;
                                $('.konten-utama').html(dataPendaftar);
                                $('.konten-utama').fadeIn(1000);
                                }
                            });
                        });
                    });
                }
            });
        });
    </script>
    {% endblock meta %}

    {% block content %}
    {% include 'navbar.html' %}
    <div class="konten-utama container p-5 my-10" style="display:none;"></div>
    <div class="modal fade" id="delete-modal" style="z-index: 1000000000;">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                <h4 class="modal-title text-dark">Please confirm data deletion!</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
    
                <!-- Modal body -->
                <div class="modal-body">
                    <p class="lead text-dark">Are you sure you want to delete your data?</p>
                </div>
    
                <!-- Modal footer -->
                <div class="modal-footer">
                <button type="button" class="confirm btn btn-danger" data-bs-dismiss="modal">Delete data</button>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}