Article/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import article_index,add_article,awal_article,getDataArticleAPI,daftarDataArticleAPI,json
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',awal_article, name='awal'),
    path('add-article',add_article,name='add article'),
    path('<str:post>',article_index,name='article index'),
    path('add-article/data-api', daftarDataArticleAPI, name='daftar'),
    path('add-article/data-article/<waktu>',getDataArticleAPI,name='data'),
    path('add-article/json',json,name='json')
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

internal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from homepage.views import index
from FeedbackPage.views import feedbackForm
from userpage.views import loginflutter, registFlutter, user_regist, loginpage, logoutuser,json, UserValidation, UserEmailValidation, PasswordValidation, user_regist_admin
from profileuser.views import get_user_data, user_profile
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name='home'),
    path('json/', json, name="json"),
    path('register/', user_regist, name='register'),
    path('register-admin/', user_regist_admin, name='register-admin'),
    path('get-profile/json', get_user_data, name='get-user-data'),
    path('login/', loginpage, name='login'),
    path('logout/', logoutuser, name='logout'),
    path('article/',include('Article.urls'), name='home'),
    path('registervaccine/', include('registervaccine.urls'), name='registervaccine'),
    path('profile/', include('profileuser.urls')),
    path('register/flutterregist', registFlutter, name="flutter-regist"),
    path('login/flutterlogin', loginflutter, name="flutter-login"),
    path('register/validation-username/', csrf_exempt(UserValidation.as_view()), name='validation-username'),
    path('register/validation-email/', csrf_exempt(UserEmailValidation.as_view()), name='validation-email'),
    path('register/validation-password/', csrf_exempt(PasswordValidation.as_view()), name='validation-password'),
    path('FeedbackPage', feedbackForm),
    path('registrasi/', include('kalender.urls')),
    path('randomgenerator/', include('randomgenerator.urls'), name='randomgenerator'),
]

kalender/urls.py
from django.urls import path
from django.urls.conf import include
from .views import *

app_name = 'registervaccine'

urlpatterns = [
    path('', registrasi, name='registrasi'),
    #path('daftar/<int:event_id>', daftar, name='daftar'),
    path('json', json, name='json'),

    #----------- urls for calendar implementation -----------------------------
    path('calenders/', CalendarView.as_view(), name='index'),
    path('event/new/', create_event, name='event_new'),
    path(
        'event/edit/<int:pk>/', EventEdit.as_view(), name='event_edit'
    ),
    path(
        'event/<int:event_id>/details/', event_details,
        name='event-detail'
    ),
    path(
        'event/<int:pk>/delete', EventDeleteView.as_view(),
        name='event_delete'
    ),
    path(
        'add_eventmember/<int:event_id>', add_eventmember,
        name='add_eventmember'
    ),
    path(
        'event/<int:pk>/remove', EventMemberDeleteView.as_view(),
        name="remove_event"
    ),
    
]

kalender/models.py
from django.db import models
from userpage.models import OriginalUser
from django.contrib.auth.models import User
from django.urls import reverse

#---------------------- Models untuk implementasi kelender ----------------------

class EventAbstract(models.Model):
    """ Event abstract model """
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class EventManager(models.Manager):
    """ Event manager """
    def get_all_events(self, user):
        events = Event.objects.filter(
            user=user, is_active=True, is_deleted=False
        )
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user, is_active=True, is_deleted=False,
            end_time__gte=datetime.now().date()
        ).order_by('start_time')
        return running_events
        
class Event(EventAbstract):
    """ Event model """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='events'
    )
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('registervaccine:event-detail', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('registervaccine:event-detail', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'


# class EventMember(EventAbstract):
#     """ Event member model """
#     event = models.ForeignKey(
#         Event, on_delete=models.CASCADE, related_name='events'
#     )
#     user = models.ForeignKey(
#         User, on_delete=models.CASCADE, related_name='event_members'
#     )

#     class Meta:
#         unique_together = ['event', 'user']

#     def __str__(self):
#         return str(self.user)

kalender/forms.py
from registervaccine.models import DataPendaftar
from .models import Event
from django import forms
from django.forms import ModelForm, DateInput, TimeInput

#-------------------- Forms for calendar implementation --------------------------

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'start_time', 'end_time']
        # datetime-local is a HTML5 input type
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter event title'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter event description'
            }),
            'date': DateInput(
                attrs={'type': 'date', 'class': 'form-control'},
                format='%Y-%m-%d'
            ),
            'start_time': TimeInput(
                attrs={'type': 'time', 'class': 'form-control', 'value': ''},
                format='%H:%M'
            ),
            'end_time': TimeInput(
                attrs={'type': 'time', 'class': 'form-control'},
                format='%H:%M'
            ),
        }
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['date'].input_formats = ('%Y-%m-%d',)
        self.fields['start_time'].input_formats = ('%H:%M',)
        self.fields['end_time'].input_formats = ('%H:%M',)


class AddMemberForm(forms.ModelForm):
    class Meta:
        model = DataPendaftar
        fields = ['username']

kalender/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import generic
from django.http.response import HttpResponseRedirect, HttpResponse
from django.utils.safestring import mark_safe
from django.core import serializers
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from django.db.models import Count
from .forms import AddMemberForm
from registervaccine.models import DataPendaftar
from datetime import timedelta, datetime, date
import calendar

from .forms import EventForm


from .models import *
from .utils import Calendar

@login_required(login_url='login')
def registrasi(request):
    context = {}
    context['events'] = Event.objects.order_by('date', 'start_time')
    context['user'] = request.user
    return render(request, 'registrasi.html', context)

def json(request):
    # Pake ini di AJAX, trus diubah jadi object javascript, tinggal dipake
    # buat nampilin yang udah didaftarin di html-nya
    data = serializers.serialize('json', Event.objects.all())
    return HttpResponse(data, content_type="application/json")

#-------------------------- Views for calendar module ---------------------------------------------

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


class CalendarView(LoginRequiredMixin, generic.ListView):
    login_url = 'login'
    model = Event
    template_name = 'calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


@login_required(login_url='signup')
def create_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        date = form.cleaned_data['date']
        start_time = form.cleaned_data['start_time']
        end_time = form.cleaned_data['end_time']
        Event.objects.get_or_create(
            user=request.user,
            title=title,
            date=date,
            description=description,
            start_time=start_time,
            end_time=end_time
        )
        return HttpResponseRedirect(reverse('registervaccine:index'))
    return render(request, 'event.html', {'form': form})


class EventEdit(generic.UpdateView):
    model = Event
    fields = ['title', 'description', 'date', 'start_time', 'end_time']
    template_name = 'event.html'


@login_required(login_url='signup')
def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    eventmember = DataPendaftar.objects.filter(event=event)
    context = {
        'event': event,
        'eventmember': eventmember
    }
    return render(request, 'event-details.html', context)

class EventDeleteView(generic.DeleteView):
    model = Event
    template_name = 'event_delete.html'
    success_url = reverse_lazy('registervaccine:index')

def add_eventmember(request, event_id):
    forms = AddMemberForm()

    if request.method == 'POST':
        forms = AddMemberForm(request.POST)

        if forms.is_valid():
            member = DataPendaftar.objects.filter(event=event_id)
            event = Event.objects.get(id=event_id)
            if member.count() <= 9:
                user = forms.cleaned_data['username']
                DataPendaftar.objects.create(
                    event=event,
                    user=user
                )
                return redirect('registervaccine:index')
            else:
                print('--------------User limit exceed!-----------------')
    context = {
        'form': forms
    }
    return render(request, 'add_member.html', context)


class EventMemberDeleteView(generic.DeleteView):
    model = DataPendaftar
    template_name = 'event_delete.html'
    success_url = reverse_lazy('registervaccine:index')

kalender/templates/add_member.html
{% extends 'master.html' %}
{% load static %}

{% block meta %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
{% endblock %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'registervaccine:index' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

kalender/templates/calendar.html
{% extends 'master.html' %}
{% load static %}

{% block meta %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
{% endblock %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 40px;">Kalender Vaksin</span>
    <a class="btn btn-info right" href="{% url 'logout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'registervaccine:index' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'registervaccine:index' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'registervaccine:event_new' %}"> + New Event </a>
    <a class="btn btn-info right mr-2" href="{% url 'registervaccine:registrasi' %}"> Back </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock content %}

kalender/templates/event-details.html
{% extends 'master.html' %}
{% load static %}

{% block meta %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
{% endblock %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'registervaccine:index' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'registervaccine:event_edit' event.pk %}"> Edit Event </a>
            <a class="btn btn-danger right mr-2" href="{% url 'registervaccine:event_delete' event.pk %}"> Delete Event </a>
        </div>
        
        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'registervaccine:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>                  
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.username.fullname }}</td>
                    <td>{{ member.username }}</td>
                    <td>{{ member.username.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'registervaccine:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

kalender/templates/event.html
{% extends 'master.html' %}
{% load static %}

{% block meta %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
{% endblock %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'registervaccine:index' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

kalender/templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'master.html' %}
{% load static %}

{% block meta %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
{% endblock %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
        <a href="{% url 'registervaccine:index' %}"><button class="btn btn-info ml-2" type="button">Back</button></a>
    </form>
{% endblock content %}

kalender/templates/registrasi.html
{% extends 'master.html' %}
{% load static %}

    {% block meta %}
    <link rel="stylesheet" href="{% static 'css/calender.css' %}" />
    <title>{%block title%}Register Vaccination{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    {% endblock meta %}

    
    {% block content %}

    <div class="container"> 
        <h1>Pilih Tanggal Vaksin</h1>
        
        {% if user.is_staff %}
        <a id="goto" href="{% url 'registervaccine:index' %}"> Go to Calendar</a>
        {% endif %}
        
        {% if numEvents == 0 %}
        <h3>Belum ada jadwal vaksin</h3>
        {% endif %}

        <table class="table">
            {% for event in events %}
            <tr>
                <td>
                    {{ event.date }}         
                </td>
                <td>{{event.start_time}}  &nbsp;&nbsp;-&nbsp;&nbsp;  {{event.end_time}}</td>
                <td><a href="{% url 'registervac:daftar' event.id %}"><button> Daftar </button></a></td>
            </tr>
            {% endfor %}
        </table>
    </div>

    {% endblock content %}